FORMAT: 1A
HOST: https://www.sysuactivity.com

# activityPlus-SYSU

ActivityPlus is an online application which provides a better way to look up, publish and manage activities for SYSU students.

## Activity Collection [/act]

### List required activities [GET /act?page={pageNum}]
List activities with the given page number.

+ Parameters
    + pageNum: `2` (number, optional) - Specified the page number
        + Default: `1`

+ Response 200 (application/json)

        {
            "content": [
                {
                    "id": 28, 
                    "name": "三月义卖", 
                    "startTime": 1521734400000,
                    "endTime": 1521820800000, 
                    "campus": 0b0000, 
                    "type": 0,
                    "poster": "imagename",
                    "location": "具体地点"
                }
            ]
        }

+ Response 204

### Get detailed activity information [GET /act/{id}]
Get activity information with the given id

+ Parameters
    + id: `9421` (number, required) - Specified the activity number
    
+ Response 200 (application/json)

        {
                "id": 21,
                "name": "sample",
                "startTime": 1521594000000,
                "endTime":1521709200000,
                "location":"三饭小广场",
                "campus":0b0001,
                "enrollCondition":"计算机学院全体学生",
                "sponsor":"SDCS团委",
                "type":2,
                "pubStartTime":1520438400000,
                "pubEndTime":1521475200000,
                "detail":"飞扬C调是计算机学院的传统活动，2018年即将迎来第11个年头；往届比赛中，无数的歌声给我们带来了很多的精彩回忆！Coding&Singing，一起来吧！",
                "verified":0b01,
                "canEnrolled":null,
                "email":null,
                "enrollWay":null,
                "enrollEndTime":null,
                "reward":null,
                "introduction":null,
                "requirement":null,
                "poster":null,
                "club":null,
                "qrcode":null
        }
    

+ Response 204

## User Collection [/users]

### User login [POST /users]
User login.

+ Request (application/json)
    + Headers

            Authorization: token_string

    + Body

            {
                "code": "string"
            }


+ Response 200 (application/json)

        {
            "token" : "64bit string"
        }

+ Response 404
+ Response 401

## Activity Apply Collection [/actApplys]

### User sign up certain activity [POST /actApplys/{actId}]
User sign up.

+ Parameters
    + actId: `1` (number, required) - Specified the activity number

+ Request (application/json)
    + Headers

            Authorization: token_string
        
    + Body

            {
                "username": "username",
                "studentid": "14223232",
                "phone": "123232323232",
                "school": "Data Science and computer"
            }

+ Response 200
+ Response 400
+ Response 401
+ Response 500

### User get registration list [GET /actApplys?page={pageNum}]
User get his/her registration list.

+ Parameters
    + pageNum: `2` (number, optional) - Specified the page number
        + Default: `1`

+ Request (application/json)

    + Headers
    
            Authorization: token_string
        
+ Response 200 (application/json)

        {
            "content": [
                {
                    "id": 28, 
                    "name": "三月义卖", 
                    "startTime": 1521734400000,
                    "endTime": 1521820800000, 
                    "campus": 0b0000, 
                    "type": 0,
                    "poster": "imagename",
                    "location": "具体地点",
                    "studentId", "15331321"
                }
            ]
        }

+ Response 204
+ Response 400
+ Response 401
+ Response 500

## Activity Discussion Collection [/discus]

### List newly discussion list [GET /discus?page={pageNum}&type={typeNum}]
List discussions with the given page number.

+ Parameters
    + pageNum: `2` (number, optional) - Specified the page number
        + Default: `1`

    + typeNum: `2` (number, required) - Specified the discussion type

    
+ Request (application/json)
    
    + Headers
    
            Authorization: token_string
    
+ Response 200 (application/json)

        {
            "content": [
                {
                    "disid": 28, 
                    "username": "oXRoe0c7KDoAVGKOTYks_kaV2iQA", 
                    "type": 2,
                    "content": "这是一条组队的帖子",
                    "time": 1521820800000
                }
            ]
        }

+ Response 401

+ Response 500

### User get comments to specific discussion [GET /discus/comments?page={pageNum}&precusor={precusorNum}]
User get comments

+ Parameters

    + pageNum: `2` (number, optional) - Specified the page number
        + Default: `1`

    + precusorNum: `2` (number, required) - Specified the target for comments

+ Request (application/json)

    + Headers
            
            Authorization: token_string
    
+ Response 200 (application/json)

        {
            "content" : [
                {
                    "cid" : 2,
                    "username" : "张三",
                    "content" : "这是一条评论",
                    "time" : 1521820800000,
                    "precusor" : 28
                }
            ]
        }

+ Response 400

+ Response 401

+ Response 500


### User sign up certain discussion [POST /discus]
User sign up his discussions

+ Request

    + Headers
    
            Authorization: token_string
        
    + Body
    
            {
                "type" : 2,
                "content" : "这是一条活动帖子"
            }
        

+ Response 200

+ Response 400

+ Response 401

+ Response 500


### User sign up comment to specified discussion [POST /discus/comments]
User sign up comment

+ Request (application/json)

    + Headers
            
            Authorization: token_string
    
    + Body
    
            {
                "content" : "这是一条评论",
                "precusor" : 28
            }

+ Response 200

+ Response 400

+ Response 401

+ Response 500